//Assignments
export const FETCH_ASSIGNMENTS = "FETCH_ASSIGNMENTS";
export const FETCH_TEAM_ASSIGNMENTS = "FETCH_TEAM_ASSIGNMENTS";
export const NEW_ASSIGNMENT = "NEW_ASSIGNMENT";

//Login
export const LOGIN = "LOGIN";

//Team
export const UPDATE_MANAGER = "UPDATE_MANAGER";
export const FETCH_TOPICS = "FETCH_TOPICS";
export const FETCH_TEAM_TREE = "FETCH_TEAM_TREE";
export const CHANGE_USER_RESTRICTIONS = "CHANGE_USER_RESTRICTIONS";
export const CHANGE_TEAM_RESTRICTIONS = "CHANGE_TEAM_RESTRICTIONS";
export const CHANGE_GLOBAL_RESTRICTIONS = "CHANGE_GLOBAL_RESTRICTIONS";
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const REASSIGN_TEAM_MEMBER = "REASSIGN_TEAM_MEMBER";
export const SELECT_CURRENT_TEAM = "SELECT_CURRENT_TEAM";

//User
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const GET_CHECK_REGISTERED = "GET_CHECK_REGISTERED";
export const FINISH_REGISTRATION = "FINISH_REGISTRATION";

//Learnt Topics
export const FETCH_EMPLOYEES_BY_TOPIC = "FETCH_EMPLOYEES_BY_TOPIC";
export const FETCH_TEAMS_BY_TOPIC = "FETCH_TEAMS_BY_TOPIC";
export const FETCH_LEARNT_TOPICS_BY_TEAM = "FETCH_LEARNT_TOPICS_BY_TEAM";
export const FETCH_PLANNED_TOPICS_BY_TEAM = "FETCH_PLANNED_TOPICS_BY_TEAM";
//Learning tree
export const LEARNING_TREE = "LEARNING_TREE";
export const LEARNING_SELECTED_USERS = "LEARNING_SELECTED_USERS";
export const SELECT_MANAGER = "SELECT_MANAGER";
export const FETCH_USER_LEARNED_TOPICS = "FETCH_USER_LEARNED_TOPICS";
export const FETCH_TEAM_LEARNED_TOPICS = "FETCH_TEAM_LEARNED_TOPICS";
export const FETCH_DESCENDANT_MANAGERS = "FETCH_DESCENDANT_MANAGERS";
export const FETCH_ALL_TOPICS = "FETCH_ALL_TOPICS";
export const RESET_DATA = "RESET_DATA";
